using System.Diagnostics;
using System.Runtime.InteropServices;

namespace U8.Shared;

static partial class U8Literals
{
    internal static class Numbers
    {
        internal const int Length = 256;

        internal static readonly U8String[] Values =
        [
            Create([(byte)'0']),
            Create([(byte)'1']),
            Create([(byte)'2']),
            Create([(byte)'3']),
            Create([(byte)'4']),
            Create([(byte)'5']),
            Create([(byte)'6']),
            Create([(byte)'7']),
            Create([(byte)'8']),
            Create([(byte)'9']),
            Create([(byte)'1', (byte)'0']),
            Create([(byte)'1', (byte)'1']),
            Create([(byte)'1', (byte)'2']),
            Create([(byte)'1', (byte)'3']),
            Create([(byte)'1', (byte)'4']),
            Create([(byte)'1', (byte)'5']),
            Create([(byte)'1', (byte)'6']),
            Create([(byte)'1', (byte)'7']),
            Create([(byte)'1', (byte)'8']),
            Create([(byte)'1', (byte)'9']),
            Create([(byte)'2', (byte)'0']),
            Create([(byte)'2', (byte)'1']),
            Create([(byte)'2', (byte)'2']),
            Create([(byte)'2', (byte)'3']),
            Create([(byte)'2', (byte)'4']),
            Create([(byte)'2', (byte)'5']),
            Create([(byte)'2', (byte)'6']),
            Create([(byte)'2', (byte)'7']),
            Create([(byte)'2', (byte)'8']),
            Create([(byte)'2', (byte)'9']),
            Create([(byte)'3', (byte)'0']),
            Create([(byte)'3', (byte)'1']),
            Create([(byte)'3', (byte)'2']),
            Create([(byte)'3', (byte)'3']),
            Create([(byte)'3', (byte)'4']),
            Create([(byte)'3', (byte)'5']),
            Create([(byte)'3', (byte)'6']),
            Create([(byte)'3', (byte)'7']),
            Create([(byte)'3', (byte)'8']),
            Create([(byte)'3', (byte)'9']),
            Create([(byte)'4', (byte)'0']),
            Create([(byte)'4', (byte)'1']),
            Create([(byte)'4', (byte)'2']),
            Create([(byte)'4', (byte)'3']),
            Create([(byte)'4', (byte)'4']),
            Create([(byte)'4', (byte)'5']),
            Create([(byte)'4', (byte)'6']),
            Create([(byte)'4', (byte)'7']),
            Create([(byte)'4', (byte)'8']),
            Create([(byte)'4', (byte)'9']),
            Create([(byte)'5', (byte)'0']),
            Create([(byte)'5', (byte)'1']),
            Create([(byte)'5', (byte)'2']),
            Create([(byte)'5', (byte)'3']),
            Create([(byte)'5', (byte)'4']),
            Create([(byte)'5', (byte)'5']),
            Create([(byte)'5', (byte)'6']),
            Create([(byte)'5', (byte)'7']),
            Create([(byte)'5', (byte)'8']),
            Create([(byte)'5', (byte)'9']),
            Create([(byte)'6', (byte)'0']),
            Create([(byte)'6', (byte)'1']),
            Create([(byte)'6', (byte)'2']),
            Create([(byte)'6', (byte)'3']),
            Create([(byte)'6', (byte)'4']),
            Create([(byte)'6', (byte)'5']),
            Create([(byte)'6', (byte)'6']),
            Create([(byte)'6', (byte)'7']),
            Create([(byte)'6', (byte)'8']),
            Create([(byte)'6', (byte)'9']),
            Create([(byte)'7', (byte)'0']),
            Create([(byte)'7', (byte)'1']),
            Create([(byte)'7', (byte)'2']),
            Create([(byte)'7', (byte)'3']),
            Create([(byte)'7', (byte)'4']),
            Create([(byte)'7', (byte)'5']),
            Create([(byte)'7', (byte)'6']),
            Create([(byte)'7', (byte)'7']),
            Create([(byte)'7', (byte)'8']),
            Create([(byte)'7', (byte)'9']),
            Create([(byte)'8', (byte)'0']),
            Create([(byte)'8', (byte)'1']),
            Create([(byte)'8', (byte)'2']),
            Create([(byte)'8', (byte)'3']),
            Create([(byte)'8', (byte)'4']),
            Create([(byte)'8', (byte)'5']),
            Create([(byte)'8', (byte)'6']),
            Create([(byte)'8', (byte)'7']),
            Create([(byte)'8', (byte)'8']),
            Create([(byte)'8', (byte)'9']),
            Create([(byte)'9', (byte)'0']),
            Create([(byte)'9', (byte)'1']),
            Create([(byte)'9', (byte)'2']),
            Create([(byte)'9', (byte)'3']),
            Create([(byte)'9', (byte)'4']),
            Create([(byte)'9', (byte)'5']),
            Create([(byte)'9', (byte)'6']),
            Create([(byte)'9', (byte)'7']),
            Create([(byte)'9', (byte)'8']),
            Create([(byte)'9', (byte)'9']),
            Create([(byte)'1', (byte)'0', (byte)'0']),
            Create([(byte)'1', (byte)'0', (byte)'1']),
            Create([(byte)'1', (byte)'0', (byte)'2']),
            Create([(byte)'1', (byte)'0', (byte)'3']),
            Create([(byte)'1', (byte)'0', (byte)'4']),
            Create([(byte)'1', (byte)'0', (byte)'5']),
            Create([(byte)'1', (byte)'0', (byte)'6']),
            Create([(byte)'1', (byte)'0', (byte)'7']),
            Create([(byte)'1', (byte)'0', (byte)'8']),
            Create([(byte)'1', (byte)'0', (byte)'9']),
            Create([(byte)'1', (byte)'1', (byte)'0']),
            Create([(byte)'1', (byte)'1', (byte)'1']),
            Create([(byte)'1', (byte)'1', (byte)'2']),
            Create([(byte)'1', (byte)'1', (byte)'3']),
            Create([(byte)'1', (byte)'1', (byte)'4']),
            Create([(byte)'1', (byte)'1', (byte)'5']),
            Create([(byte)'1', (byte)'1', (byte)'6']),
            Create([(byte)'1', (byte)'1', (byte)'7']),
            Create([(byte)'1', (byte)'1', (byte)'8']),
            Create([(byte)'1', (byte)'1', (byte)'9']),
            Create([(byte)'1', (byte)'2', (byte)'0']),
            Create([(byte)'1', (byte)'2', (byte)'1']),
            Create([(byte)'1', (byte)'2', (byte)'2']),
            Create([(byte)'1', (byte)'2', (byte)'3']),
            Create([(byte)'1', (byte)'2', (byte)'4']),
            Create([(byte)'1', (byte)'2', (byte)'5']),
            Create([(byte)'1', (byte)'2', (byte)'6']),
            Create([(byte)'1', (byte)'2', (byte)'7']),
            Create([(byte)'1', (byte)'2', (byte)'8']),
            Create([(byte)'1', (byte)'2', (byte)'9']),
            Create([(byte)'1', (byte)'3', (byte)'0']),
            Create([(byte)'1', (byte)'3', (byte)'1']),
            Create([(byte)'1', (byte)'3', (byte)'2']),
            Create([(byte)'1', (byte)'3', (byte)'3']),
            Create([(byte)'1', (byte)'3', (byte)'4']),
            Create([(byte)'1', (byte)'3', (byte)'5']),
            Create([(byte)'1', (byte)'3', (byte)'6']),
            Create([(byte)'1', (byte)'3', (byte)'7']),
            Create([(byte)'1', (byte)'3', (byte)'8']),
            Create([(byte)'1', (byte)'3', (byte)'9']),
            Create([(byte)'1', (byte)'4', (byte)'0']),
            Create([(byte)'1', (byte)'4', (byte)'1']),
            Create([(byte)'1', (byte)'4', (byte)'2']),
            Create([(byte)'1', (byte)'4', (byte)'3']),
            Create([(byte)'1', (byte)'4', (byte)'4']),
            Create([(byte)'1', (byte)'4', (byte)'5']),
            Create([(byte)'1', (byte)'4', (byte)'6']),
            Create([(byte)'1', (byte)'4', (byte)'7']),
            Create([(byte)'1', (byte)'4', (byte)'8']),
            Create([(byte)'1', (byte)'4', (byte)'9']),
            Create([(byte)'1', (byte)'5', (byte)'0']),
            Create([(byte)'1', (byte)'5', (byte)'1']),
            Create([(byte)'1', (byte)'5', (byte)'2']),
            Create([(byte)'1', (byte)'5', (byte)'3']),
            Create([(byte)'1', (byte)'5', (byte)'4']),
            Create([(byte)'1', (byte)'5', (byte)'5']),
            Create([(byte)'1', (byte)'5', (byte)'6']),
            Create([(byte)'1', (byte)'5', (byte)'7']),
            Create([(byte)'1', (byte)'5', (byte)'8']),
            Create([(byte)'1', (byte)'5', (byte)'9']),
            Create([(byte)'1', (byte)'6', (byte)'0']),
            Create([(byte)'1', (byte)'6', (byte)'1']),
            Create([(byte)'1', (byte)'6', (byte)'2']),
            Create([(byte)'1', (byte)'6', (byte)'3']),
            Create([(byte)'1', (byte)'6', (byte)'4']),
            Create([(byte)'1', (byte)'6', (byte)'5']),
            Create([(byte)'1', (byte)'6', (byte)'6']),
            Create([(byte)'1', (byte)'6', (byte)'7']),
            Create([(byte)'1', (byte)'6', (byte)'8']),
            Create([(byte)'1', (byte)'6', (byte)'9']),
            Create([(byte)'1', (byte)'7', (byte)'0']),
            Create([(byte)'1', (byte)'7', (byte)'1']),
            Create([(byte)'1', (byte)'7', (byte)'2']),
            Create([(byte)'1', (byte)'7', (byte)'3']),
            Create([(byte)'1', (byte)'7', (byte)'4']),
            Create([(byte)'1', (byte)'7', (byte)'5']),
            Create([(byte)'1', (byte)'7', (byte)'6']),
            Create([(byte)'1', (byte)'7', (byte)'7']),
            Create([(byte)'1', (byte)'7', (byte)'8']),
            Create([(byte)'1', (byte)'7', (byte)'9']),
            Create([(byte)'1', (byte)'8', (byte)'0']),
            Create([(byte)'1', (byte)'8', (byte)'1']),
            Create([(byte)'1', (byte)'8', (byte)'2']),
            Create([(byte)'1', (byte)'8', (byte)'3']),
            Create([(byte)'1', (byte)'8', (byte)'4']),
            Create([(byte)'1', (byte)'8', (byte)'5']),
            Create([(byte)'1', (byte)'8', (byte)'6']),
            Create([(byte)'1', (byte)'8', (byte)'7']),
            Create([(byte)'1', (byte)'8', (byte)'8']),
            Create([(byte)'1', (byte)'8', (byte)'9']),
            Create([(byte)'1', (byte)'9', (byte)'0']),
            Create([(byte)'1', (byte)'9', (byte)'1']),
            Create([(byte)'1', (byte)'9', (byte)'2']),
            Create([(byte)'1', (byte)'9', (byte)'3']),
            Create([(byte)'1', (byte)'9', (byte)'4']),
            Create([(byte)'1', (byte)'9', (byte)'5']),
            Create([(byte)'1', (byte)'9', (byte)'6']),
            Create([(byte)'1', (byte)'9', (byte)'7']),
            Create([(byte)'1', (byte)'9', (byte)'8']),
            Create([(byte)'1', (byte)'9', (byte)'9']),
            Create([(byte)'2', (byte)'0', (byte)'0']),
            Create([(byte)'2', (byte)'0', (byte)'1']),
            Create([(byte)'2', (byte)'0', (byte)'2']),
            Create([(byte)'2', (byte)'0', (byte)'3']),
            Create([(byte)'2', (byte)'0', (byte)'4']),
            Create([(byte)'2', (byte)'0', (byte)'5']),
            Create([(byte)'2', (byte)'0', (byte)'6']),
            Create([(byte)'2', (byte)'0', (byte)'7']),
            Create([(byte)'2', (byte)'0', (byte)'8']),
            Create([(byte)'2', (byte)'0', (byte)'9']),
            Create([(byte)'2', (byte)'1', (byte)'0']),
            Create([(byte)'2', (byte)'1', (byte)'1']),
            Create([(byte)'2', (byte)'1', (byte)'2']),
            Create([(byte)'2', (byte)'1', (byte)'3']),
            Create([(byte)'2', (byte)'1', (byte)'4']),
            Create([(byte)'2', (byte)'1', (byte)'5']),
            Create([(byte)'2', (byte)'1', (byte)'6']),
            Create([(byte)'2', (byte)'1', (byte)'7']),
            Create([(byte)'2', (byte)'1', (byte)'8']),
            Create([(byte)'2', (byte)'1', (byte)'9']),
            Create([(byte)'2', (byte)'2', (byte)'0']),
            Create([(byte)'2', (byte)'2', (byte)'1']),
            Create([(byte)'2', (byte)'2', (byte)'2']),
            Create([(byte)'2', (byte)'2', (byte)'3']),
            Create([(byte)'2', (byte)'2', (byte)'4']),
            Create([(byte)'2', (byte)'2', (byte)'5']),
            Create([(byte)'2', (byte)'2', (byte)'6']),
            Create([(byte)'2', (byte)'2', (byte)'7']),
            Create([(byte)'2', (byte)'2', (byte)'8']),
            Create([(byte)'2', (byte)'2', (byte)'9']),
            Create([(byte)'2', (byte)'3', (byte)'0']),
            Create([(byte)'2', (byte)'3', (byte)'1']),
            Create([(byte)'2', (byte)'3', (byte)'2']),
            Create([(byte)'2', (byte)'3', (byte)'3']),
            Create([(byte)'2', (byte)'3', (byte)'4']),
            Create([(byte)'2', (byte)'3', (byte)'5']),
            Create([(byte)'2', (byte)'3', (byte)'6']),
            Create([(byte)'2', (byte)'3', (byte)'7']),
            Create([(byte)'2', (byte)'3', (byte)'8']),
            Create([(byte)'2', (byte)'3', (byte)'9']),
            Create([(byte)'2', (byte)'4', (byte)'0']),
            Create([(byte)'2', (byte)'4', (byte)'1']),
            Create([(byte)'2', (byte)'4', (byte)'2']),
            Create([(byte)'2', (byte)'4', (byte)'3']),
            Create([(byte)'2', (byte)'4', (byte)'4']),
            Create([(byte)'2', (byte)'4', (byte)'5']),
            Create([(byte)'2', (byte)'4', (byte)'6']),
            Create([(byte)'2', (byte)'4', (byte)'7']),
            Create([(byte)'2', (byte)'4', (byte)'8']),
            Create([(byte)'2', (byte)'4', (byte)'9']),
            Create([(byte)'2', (byte)'5', (byte)'0']),
            Create([(byte)'2', (byte)'5', (byte)'1']),
            Create([(byte)'2', (byte)'5', (byte)'2']),
            Create([(byte)'2', (byte)'5', (byte)'3']),
            Create([(byte)'2', (byte)'5', (byte)'4']),
            Create([(byte)'2', (byte)'5', (byte)'5'])
        ];

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static bool IsInRange(nint value)
        {
            return (nuint)value < Length;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static U8String GetValueUnchecked(nint value)
        {
            Debug.Assert((nuint)value < Length);
            return Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(Values), value);
        }

        static U8String Create(ReadOnlySpan<byte> values)
        {
            Debug.Assert(values.Length > 0);
            var pinned = GC.AllocateArray<byte>(values.Length + 1, pinned: true);
            values.CopyTo(pinned);
            return new U8String(pinned, values.Length, neverEmpty: true);
        }
    }
}
