name: tests-extra

on: [push, pull_request]

jobs:
  tests-extra:
    name: tests-extra on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
          include-prerelease: true
      - name: Restore dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test --no-restore
        env:
          DOTNET_EnableAVX512F: 1
      - name: Test Release x86
        if: matrix.os == 'windows-latest'
        run: dotnet test -c Release -a x86 --no-restore
      - name: Test Release x64
        run: dotnet test -c Release --no-restore
        env:
          DOTNET_EnableAVX512F: 1